# Generated by Django 4.0.3 on 2022-03-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admissions_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_group_code', models.IntegerField(verbose_name='专业组代码')),
            ],
        ),
    ]
