# Generated by Django 4.0.3 on 2022-03-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yingding', '0002_admissions_data_annual_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions_data',
            name='major_group_name',
            field=models.CharField(default='', max_length=80, verbose_name='专业组名称'),
        ),
    ]
